### PR TITLE
Add typescript support

### PR DESCRIPTION
**Pull request by pszalanski**
Add the solution proposed in #6

### CODE REVIEW

**Comment by heidkaemper** [comment]
First of all, thank you for that!
But typescript in devDependencies and tsconfig.json are not necessary unless you want to build this addon with Typescript, right?

**Comment by pszalanski** [comment]
Yes, for users without typescript, this would be an unused dependency. I was under the impression that you would not like to have a separate library, which only adds typescript support. 

I have never worked with vanilla javascript, except maybe using jquery, 15 years ago. So I assumed that adding typescript is self-evident, regardless of the additional dependencies  😄 

How would you like to proceed? I could create a project for "DefinetelyTyped", which adds typescript support to JS libraries, using separate, optional packages only for typescript users.

**Comment by heidkaemper** [comment]
To be clear, we will definitely add the index.d.ts file for Typescript users.

But if you have a project based on Tailwind CSS, Typescript and this plugin, your `package.json` would look something like this, right?
```
"devDependencies": {
    "tailwindcss": "*",
    "tailwindcss-animated": "*",
    "typescript": "*"
},
```
So why would you need Typescript as a dependency in our tailwindcss-animated package as well?

**Comment by pszalanski** [comment]
You are right, I added the `tsconfig.json` and the dependency at the same time. It still works after removing typescript.

**Comment by heidkaemper** [comment]
@pszalanski I made a few changes and moved the `index.d.ts` to the `src` folder. But it's finally released now! 🎉

Thanks for you contribution!

**Pull request merged**
